apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitnut.fullname" . }}-secrets
  labels:
    {{- include "gitnut.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  WALLET_SIGNIN_DOMAIN: {{ .Values.secrets.walletSigninDomain | quote }}
