apiVersion: apps/v1
kind: Deployment
metadata:
  name: { include "gitnut.fullname" . }-worker
  labels:
    {- include "gitnut.labels" . | nindent 4 }
    app.gitnut.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: { .Release.Name }
      app.gitnut.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: { .Release.Name }
        app.gitnut.io/component: worker
        {- include "gitnut.labels" . | nindent 12 }
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.registry }}/gitnut-worker:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: { include "gitnut.fullname" . }-config
            - secretRef:
                name: { include "gitnut.fullname" . }-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {- toYaml .Values.resources.worker | nindent 16 }
---
apiVersion: v1
kind: Service
metadata:
  name: { include "gitnut.fullname" . }-worker
  labels:
    {- include "gitnut.labels" . | nindent 4 }
    app.gitnut.io/component: worker
spec:
  selector:
    app.kubernetes.io/instance: { .Release.Name }
    app.gitnut.io/component: worker
  ports:
    - name: http
      port: 8081
      targetPort: http
