apiVersion: v1
kind: Secret
metadata:
  name: gitnut-secrets
  namespace: gitnut
type: Opaque
stringData:
  POSTGRES_USER: "gitnut"
  POSTGRES_PASSWORD: "gitnut"
  MINIO_ROOT_USER: "gitnut"
  MINIO_ROOT_PASSWORD: "gitnut-password-change-me"
  GITHUB_CLIENT_ID: "replace"
  GITHUB_CLIENT_SECRET: "replace"
  JWT_SECRET: "replace-with-strong-secret"
  SESSION_SECRET: "replace-with-strong-secret"
  WALLET_SIGNIN_DOMAIN: "gitnut.example.com"
