apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitnut

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/secret.yaml
  - ../../base/postgres.yaml
  - ../../base/redis.yaml
  - ../../base/api.yaml
  - ../../base/worker.yaml
  - ../../base/web.yaml
  - ../../base/indexer.yaml
  - ../../base/ingress.yaml

images:
  - name: ghcr.io/gitnut/gitnut-api
    newTag: local
  - name: ghcr.io/gitnut/gitnut-web
    newTag: local
  - name: ghcr.io/gitnut/gitnut-worker
    newTag: local
  - name: ghcr.io/gitnut/gitnut-indexer
    newTag: local

patches:
  - target:
      kind: Ingress
      name: gitnut-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: gitnut.local
      - op: replace
        path: /spec/rules/1/host
        value: api.gitnut.local
