apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitnut

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/secret.yaml
  - ../../base/postgres.yaml
  - ../../base/redis.yaml
  - ../../base/api.yaml
  - ../../base/worker.yaml
  - ../../base/web.yaml
  - ../../base/indexer.yaml
  - ../../base/ingress.yaml

replicas:
  - name: api
    count: 2
  - name: web
    count: 2
  - name: worker
    count: 1
  - name: indexer
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: gitnut-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: gitnut-config
        namespace: gitnut
      data:
        NODE_ENV: "staging"
        LOG_LEVEL: "debug"
